# Generated by Django 5.2.2 on 2025-06-07 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('transactionSum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transactionDate', models.DateField()),
                ('transactionDescription', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('transactionSum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transactionDate', models.DateField()),
                ('transactionDescription', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.category')),
            ],
        ),
    ]
